In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
df = pd.read_csv("/Volumes/Desk_Data/backtesting/BTCUSD-1m-2026-01.csv")
df.columns = [
    "open_time",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "close_time",
    "quote_volume",
    "num_trades",
    "taker_base",
    "taker_quote",
    "ignore"
]

In [5]:
df["open_time"] = pd.to_datetime(
    df["open_time"],
    unit="us",
    utc=True
)

df["close_time"] = pd.to_datetime(
    df["close_time"],
    unit="us",
    utc=True
)

In [6]:
df.head()

,open_time,open,high,low,close,volume,close_time,quote_volume,num_trades,taker_base,taker_quote,ignore
0,2026-01-01 00:01:00+00:00,87552.07,87552.07,87552.07,87552.07,0.00000,2026-01-01 00:01:59.999999+00:00,0.000000,0,0.00000,0.000000,0
1,2026-01-01 00:02:00+00:00,87552.07,87552.07,87552.07,87552.07,0.00000,2026-01-01 00:02:59.999999+00:00,0.000000,0,0.00000,0.000000,0
2,2026-01-01 00:03:00+00:00,87626.01,87626.01,87626.01,87626.01,0.00431,2026-01-01 00:03:59.999999+00:00,377.668103,2,0.00431,377.668103,0
3,2026-01-01 00:04:00+00:00,87626.01,87626.01,87626.01,87626.01,0.00000,2026-01-01 00:04:59.999999+00:00,0.000000,0,0.00000,0.000000,0
4,2026-01-01 00:05:00+00:00,87626.01,87626.01,87626.01,87626.01,0.00000,2026-01-01 00:05:59.999999+00:00,0.000000,0,0.00000,0.000000,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44639 entries, 0 to 44638
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   open_time     44639 non-null  datetime64[ns, UTC]
 1   open          44639 non-null  float64
 2   high          44639 non-null  float64
 3   low           44639 non-null  float64
 4   close         44639 non-null  float64
 5   volume        44639 non-null  float64
 6   close_time    44639 non-null  datetime64[ns, UTC]
 7   quote_volume  44639 non-null  float64
 8   num_trades    44639 non-null  int64
 9   taker_base    44639 non-null  float64
 10  taker_quote   44639 non-null  float64
 11  ignore        44639 non-null  int64
dtypes: datetime64[ns, UTC](2), float64(8), int64(2)
memory usage: 4.1 MB

In [8]:


df["date"] = df["open_time"].dt.date
df["hour"] = df["open_time"].dt.hour

df[["open_time", "date", "hour"]].tail()

                      open_time        date  hour
44634 2026-01-31 23:55:00+00:00  2026-01-31    23
44635 2026-01-31 23:56:00+00:00  2026-01-31    23
44636 2026-01-31 23:57:00+00:00  2026-01-31    23
44637 2026-01-31 23:58:00+00:00  2026-01-31    23
44638 2026-01-31 23:59:00+00:00  2026-01-31    23

In [9]:
def get_session(hour):

    if 0 <= hour < 8:
        return "Asia"

    elif 8 <= hour < 13:
        return "London"

    elif 13 <= hour < 21:
        return "NewYork"

    else:
        return "Other"


df["session"] = df["hour"].apply(get_session)

In [10]:
#############

In [11]:
daily_data = []

In [12]:
len(df["date"].unique())

31

In [13]:
ˇ

NameError: name 'ˇ' is not defined